<a href="https://colab.research.google.com/github/fegasu/python/blob/master/VacasLeche.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import numpy as np


In [103]:

nfil=int(input("Cuantos días: "))
ncol=int(input("Cuantas Vacas: "))
M=np.zeros((nfil,ncol))
print(M)

Cuantos días: 5
Cuantas Vacas: 3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [104]:
for i in range(nfil):
  for j in range(ncol):
    M[i][j]=int(input("Cantidad de litros de leche: "))

Cantidad de litros de leche: 4
Cantidad de litros de leche: 5
Cantidad de litros de leche: 1
Cantidad de litros de leche: 8
Cantidad de litros de leche: 5
Cantidad de litros de leche: 4
Cantidad de litros de leche: 3
Cantidad de litros de leche: 2
Cantidad de litros de leche: 1
Cantidad de litros de leche: 1
Cantidad de litros de leche: 2
Cantidad de litros de leche: 3
Cantidad de litros de leche: 4
Cantidad de litros de leche: 5
Cantidad de litros de leche: 6


In [105]:
print(M)

[[4. 5. 1.]
 [8. 5. 4.]
 [3. 2. 1.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [120]:
Sume=lambda M: [ sum(i) for i in M]
x=Sume(M)
y=[]
y=np.zeros(nfil)
y[0]=3
print(M)
print("**************")
for i in range(nfil):
  print("Leche "+str(i+1)+" dia: "+str(x[i]))



[[4. 5. 1.]
 [8. 5. 4.]
 [3. 2. 1.]
 [1. 2. 3.]
 [4. 5. 6.]]
**************
Leche 1 dia: 10.0
Leche 2 dia: 17.0
Leche 3 dia: 6.0
Leche 4 dia: 6.0
Leche 5 dia: 15.0


In [122]:
for i in range(nfil):
  print(M[i])
  z=max(M[i])
  w=list(M[i])
  y[i]=w.index(z)
print("**************")
for i in range(nfil):
  print("El "+str(i+1)+" dia la vaca que mas dio leche fue="+str(y[i]+1))


[4. 5. 1.]
[8. 5. 4.]
[3. 2. 1.]
[1. 2. 3.]
[4. 5. 6.]
**************
El 1 dia la vaca que mas dio leche fue=2.0
El 2 dia la vaca que mas dio leche fue=1.0
El 3 dia la vaca que mas dio leche fue=1.0
El 4 dia la vaca que mas dio leche fue=3.0
El 5 dia la vaca que mas dio leche fue=3.0
